In [25]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.io as pio
pio.renderers.defaule = 'colab'

from itables import show

In [26]:
DF_raw = pd.read_csv('BMW_sales_data.csv')
DF = pd.read_csv('BMW_sales_data.csv')
DF

,Model,Year,Region,Color,Fuel_Type,Transmission,Engine_Size_L,Mileage_KM,Price_USD,Sales_Volume,Sales_Classification
0,5 Series,2016,Asia,Red,Petrol,Manual,3.5,151748,98740,8300,High
1,i8,2013,North America,Red,Hybrid,Automatic,1.6,121671,79219,3428,Low
2,5 Series,2022,North America,Blue,Petrol,Automatic,4.5,10991,113265,6994,Low
3,X3,2024,Middle East,Blue,Petrol,Automatic,1.7,27255,60971,4047,Low
4,7 Series,2020,South America,Black,Diesel,Manual,2.1,122131,49898,3080,Low
...,...,...,...,...,...,...,...,...,...,...,...
49995,i3,2014,Asia,Red,Hybrid,Manual,4.6,151030,42932,8182,High
49996,i3,2023,Middle East,Silver,Electric,Manual,4.2,147396,48714,9816,High
49997,5 Series,2010,Middle East,Red,Petrol,Automatic,4.5,174939,46126,8280,High
49998,i3,2020,Asia,White,Electric,Automatic,3.8,3379,58566,9486,High
49999,X1,2020,North America,Blue,Diesel,Manual,3.3,171003,77492,1764,Low

Intro

Does price predict higher or lower sales? Is there a correlation in price and region? Are certain fuel types becoming more popular?

This is an important topic to me because I can connect this directly to my economics major, one of my favorite things to do in my free time is analyze luxury cars, and get a better understanding of consumer behavior and market trends with decision making.

I am hoping to find meaningful patterns in BMW sales over time, understand which features have the biggest impact on sales volume, and produce visualizations that clearly show trends and relationships.

Description

I downloaded this free data off of Kaggle, it was a shock to me to find out after googling that most free downloadable datasets always raise privacy, concent, bias, transparency, and accountability concerns.

make and model, year of production, region where car sold, exterior color, type of fuel, type of transmission, engine displscement in liters, total milage driven in km, USD price, number of cars sold, high or medium or low sales

In [27]:
DF.describe()

               Year  Engine_Size_L     Mileage_KM      Price_USD  Sales_Volume
count  50000.000000   50000.000000   50000.000000   50000.000000  50000.000000
mean    2017.015700       3.247180  100307.203140   75034.600900   5067.514680
std        4.324459       1.009078   57941.509344   25998.248882   2856.767125
min     2010.000000       1.500000       3.000000   30000.000000    100.000000
25%     2013.000000       2.400000   50178.000000   52434.750000   2588.000000
50%     2017.000000       3.200000  100388.500000   75011.500000   5087.000000
75%     2021.000000       4.100000  150630.250000   97628.250000   7537.250000
max     2024.000000       5.000000  199996.000000  119998.000000   9999.000000

In [28]:
DF.shape

(50000, 11)

In [29]:
DF['Price_USD'].value_counts

<bound method IndexOpsMixin.value_counts of 0         98740
1         79219
2        113265
3         60971
4         49898
          ...
49995     42932
49996     48714
49997     46126
49998     58566
49999     77492
Name: Price_USD, Length: 50000, dtype: int64>

In [30]:
DF['Price_USD'].max()

119998

In [31]:
DF['Price_USD'].min()

30000

In [32]:
DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Model                 50000 non-null  object
 1   Year                  50000 non-null  int64
 2   Region                50000 non-null  object
 3   Color                 50000 non-null  object
 4   Fuel_Type             50000 non-null  object
 5   Transmission          50000 non-null  object
 6   Engine_Size_L         50000 non-null  float64
 7   Mileage_KM            50000 non-null  int64
 8   Price_USD             50000 non-null  int64
 9   Sales_Volume          50000 non-null  int64
 10  Sales_Classification  50000 non-null  object
dtypes: float64(1), int64(4), object(6)
memory usage: 4.2+ MB

In [33]:
DF_price = DF['Price_USD'].value_counts().head(10)
DF_price

Price_USD
30948     6
79587     5
51926     5
76399     5
42383     5
104818    5
51122     5
67539     5
103505    5
77120     5
Name: count, dtype: int64

In [34]:
p_f = DF.groupby('Fuel_Type')['Price_USD'].mean()
p_f

Fuel_Type
Diesel      75079.809671
Electric    75276.313207
Hybrid      74797.551746
Petrol      74990.419841
Name: Price_USD, dtype: float64

What factors strongly influence BMW sales volume?

- predict price based on features like mileage, year, engine size, transmission, and fuel type

- categorical features to predict monthly or annual sales

- forecasting for sales trends by region or model over years

- buying/reselling strategies based on car features, mileage, and region

- insights into consumer preferences like color, fuel type, transmission